using UnityEngine;

public class ColliderSystem : MonoBehaviour
{
    // Start is called before the first frame update
    private void ManagerCollision(GameObject Collision) {
        switch (Collision.tag)
        {
            case "Floor":
                // C贸digo para fazer algo
                break;
            case "Obstacle":
                // C贸digo para fazer algo
                break;
            case "Enemy":
                // C贸digo para fazer algo
                break;
            case "Wall":
                // C贸digo para fazer algo
                break;
            default:
                break;
        }   
    }

    private void OnCollisionEnter2D(Collision2D other) {
        ManagerCollision(other.gameObject);
    }
}
